---
title: "2023 February Sampling"
author: "Nargol Ghazian"
date: '2023-02-02'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
###Questions for Shelter Project
#1. To what extent does the natural fabric burlap affect microclimatic parameters such as relative humidity (RH), temperature, and light intensity under the shelter canopy in the winter? 
#2. Is there a significant difference in the above measurements for differently-shaped shelters? 
#3. Is there a difference in how the shelters affect the above parameters at a southern, dry site versus  milder sites in the north?
#4. Is the variation significant between climatic measurements taken using data loggers and versus a handheld device?
#5. How do natural shrubs compare to artificial shetlers in terms of impacting the canopy microclimate?
  
###Questions for shrub handheld experiment. 
#1. How does shrub size influence canopy temperature and humidity?
#2. How do logger recording compare to handheld recordings?
#3. How does microclimate of shrubs differ in northern sites versus southern sites?

```

```{r}
###Sample datasheets
library(tidyverse)

#location of shelters and shrub
df1<-read.csv("C:/Users/Nargol Ghazian/Desktop/PhD-Shelter-Shrub-Climate/Field Season 2022/sample shelter.csv") 
knitr::kable(df1)

     

#microclimate handheld for shelter shrubs
df2<-read.csv("C:/Users/Nargol Ghazian/Desktop/PhD-Shelter-Shrub-Climate/Field Season 2022/Datasheets/Compiled Handheld climate_2022.csv")
knitr::kable(df2)


#microclimate handheld
df3<-read.csv("C:/Users/Nargol Ghazian/Desktop/PhD-Shelter-Shrub-Climate/Field Season 2022/Datasheets/shrub size and microclimate.csv")
knitr::kable(df3)

```


```{r}
###methods

##shelters
#1. Build 8 shelters in total (4 square, 4 triangle)in Carrizo sites 3 and 4 and pair with shrubs. Do the same in Tecopa. Build 4 shelters in soda lake open (2 of each kind) and do the same in Tecopa_open.
#2. Put hobo and omega loggers underneth all and the shrubs.
#3. Measure handheld climate data twice.

##shrub size experiement
#1. Put hobo loggers undearneath 5 shrubs and 5 opens in Cuyama 1 and 2
#2. Measure handheld climate at those 5 shrubs and opens + another 5 at least twice.
#3. Do point measurements at any sites you are going to once (e.x. Semitropics, cuyama 3, 5, 6, Avenal maaybe)
```


```{r}
###Big picture

#1. Have winter data in case refree asks what if shelters only cool when it is super dry and hot.

#2. One more paper for shrub gradient. 
```

