---
title: "Camtrap Review"
author: "Nargol Ghazian"
date: "30/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#import data 

library (tidyr)
library (tidyverse)
library (dplyr)
library(ggplot2)


data_cam<-read.csv("C:/Users/Nargol Ghazian/Desktop/PhD-Shelter-Shrub-Climate/Camtrap Review/review camtrap final.csv") %>% 
  filter(bait == "no" & ecosystem != "aquatic") 
library (tidyr)
library (tidyverse)
library (dplyr)
library(ggplot2)

#some data VIZ
na.omit (data_cam)


ggplot(data_cam, aes((ecosystem), fill=ecosystem)) + geom_bar()+ labs(x = "Ecosystem", y = "Number of Studies")+theme_classic()+theme(axis.text.x = element_text(angle = 90))+ theme(legend.position = "none")


ggplot(data_cam, aes(n_sites))+geom_bar()

ggplot(data_cam, aes((number.cams), fill=ecosystem)) + geom_bar() + xlab("Ecosystem") + ylab ("Number of Camera Traps")+ theme_classic()+
theme(axis.text=element_text(size=12))+theme(axis.text.x = element_text(angle = 90))+ labs(fill = "Ecosystem")+ theme(axis.text.x = element_text(angle = 90))

ggplot(data_cam, aes(number.cams, captures)) +
  geom_point() + 
  stat_smooth(method = "lm", se = FALSE)+ theme_classic ()

ggplot(data_cam, aes(days, captures)) +
  geom_point() +
  stat_smooth(method = "lm", se = FALSE)


```


```{r}
#EDA
#explore normality 

library(ggpubr)
ggqqplot(data_cam$richness)#data look Gaussian
hist(data_cam$richness)
ggqqplot(data_cam$n_sites)
hist(data_cam$n_sites)#data look right-skewed 

shapiro.test(data_cam$richness) #p<0.05 data is not normal
shapiro.test(data_cam$n_sites) #p<0.05 data is not normal
```


```{r}
#RARE CURVES

library (iNEXT)
out <- iNEXT(data_cam, q= 0, datatype = "abundance", endpoint = 80000) #error because "Zero abundance counts in one or more sample sites"

ggiNEXT(out, type= 1, facet.var= "ecosystem")

library (vegan)#another way we may be able to do it
data_cam2 <- data_cam [0:8000,]
raremx <-min (rowSums(data_cam2))

rarecurve(data_cam, step = 20, sample = raremax, col = col,
                      lty = lty, label = FALSE)

```

