---
title: "Global Models Chapter 4"
author: "Nargol Ghazian"
date: "2024-04-03"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library (ggplot2)
library (tidyverse)
library (dplyr)
library (emmeans)
library (sjPlot)
library(ggpubr)
library(patchwork)
library(tidyr)
```

```{r}
##Hypothesis 1: Species communities are the same across all microsites.
##Tested via PCOA for spring only and it was the same across all microsites.

##Hypothesis 2: The number of animals that associate with shrubs and shelters is similar and different from the open. The number of different species that associate with shrubs and shelters is also similar, and different from the open.
##Tested via GLM models with microsite nested in site and year as a random factor.
##tested for both the spring.
##There are differences in abundance, richness, and evenness in microsites across sites. Microsite:site_code is significant for all three measures.
##winter data outputs a lot of NaN.

##Hypothesis 3: Animals associate with shrubs and shelters more than the open because they are cooler, more humid, and experience less direct solar radiation.
##Checked PCA and humidity and temp are collinear. PCA eigenvalue was less<1 and PC1 only explained 69% percent of the variation.
##Used performance model to check collinearity. AIC scores showed humidity is a better predictor in models.
##tested for spring data: nor humidity or intensity was a predictor of abundance, intensity a predictor of richness, and both humidity and intensity are predictors of evenness.

##winter does not have humidity, so we used temp. temp and intensity were significant predictors of abundance, intensity was a significant predictor of richness, and none predicted evenness.



```

```{r}
###load the three main data packages

microclimate_hourly<- read.csv("C:/Users/Nargol Ghazian/Desktop/PhD-Shelter-Shrub-Climate/shelters/global model files/microclimate_hourly.csv")
animals_compiled<-read.csv("C:/Users/Nargol Ghazian/Desktop/PhD-Shelter-Shrub-Climate/shelters/global model files/animals_compiled.csv")
animal_species_compiled <-read.csv("C:/Users/Nargol Ghazian/Desktop/PhD-Shelter-Shrub-Climate/shelters/global model files/animal_species_compiled.csv")
sites<-read.csv("C:/Users/Nargol Ghazian/Desktop/PhD-Shelter-Shrub-Climate/shelters/global model files/sites.csv")

```

```{r}
###summarize and join microclimate to animals_compiled
na.omit(microclimate_hourly)

microclimate_summarized<-microclimate_hourly %>%
  group_by(site_code, microsite, season, year, region) %>% 
  summarise (mean_temp = mean(temp, na.rm=T), mean_intensity = mean(intensity, na.rm = T), mean_humidity = mean(humidity, na.rm = T))

microclimate_animals_compiled<-merge(microclimate_summarized, animals_compiled, by = c("site_code", "microsite", "region", "year", "season"))


###filter out winter data from summarized data

microclimate_animals_compiled_winter <-microclimate_animals_compiled%>%filter(season =="winter") 

microclimate_animals_compiled<-microclimate_animals_compiled%>%filter(season =="spring")###for PCOA and PCA

```

```{r}
###Run a PCOA of the global, spring data to see if community composition differs across microsites.
###Hypothesis: Community composition is the same across all microsites.


library(ape)
library(vegan)
library(permute)

microclimate_animals_compiled<-microclimate_animals_compiled%>%filter(season =="spring")###Run a PCOA for spring only 


pcoa_data_final <-  animal_species_compiled%>%
  spread(scientific_name, captures) %>%
  replace(is.na(.),0)%>% ungroup() %>% dplyr::select(-microsite, -year, - region, -site_code, -season, -total, -percent_proportion, -rep_continous)
dim(pcoa_data_final)

pcoa_mod<-adonis(pcoa_data_final ~ microsite, data = animal_species_compiled)
pcoa_mod


dist_final <- vegdist(pcoa_data_final, species = "bray")
res_final <- pcoa(dist_final)
p01 <- as.data.frame(res_final$vectors)%>%
  dplyr::select(Axis.1, Axis.2) %>%
  bind_cols(animal_species_compiled,.)


ggplot() + 
  geom_point(data = p01, aes(x = Axis.1, y = Axis.2, color = microsite))+ theme_classic()+ theme(panel.border = element_rect(color = "black",
                                    fill = NA,
                                    size = 1))+ labs(color = "Microsite") 



model1<-betadisper(dist_final, animal_species_compiled$microsite)
anova(model1)
TukeyHSD(model1)###community composition does not differ across microsites. 
permutest(model1, pairwise = TRUE)
boxplot(model1, xlab = "Microsite")



```

```{r}
###GLMs.
###Q: Did animals associate with shrubs and shelters to the same extent and both different from shrubs? 
###Hypothesis: Animals associate with shelters and shrubs equally, and with both more than the open gap. The number of species that associate with shelters and shrubs is similar and different from the open.
###spring


mod1.1<-glm(abundance~microsite%in%site_code + (1 | year), data = microclimate_animals_compiled)
anova(mod1.1, test = "Chisq")
tab_model(mod1.1)
emmeans(mod1.1, pairwise~microsite|site_code)
          
mod1.2<-glm(richness~microsite %in% site_code + (1 | year), data = microclimate_animals_compiled)
anova(mod1.2, test = "Chisq")
tab_model(mod1.2)
emmeans(mod1.1, pairwise~microsite|site_code)
          
mod1.3<-glm(evenness~microsite %in% site_code + (1 | year), data = microclimate_animals_compiled)
anova(mod1.3, test = "Chisq")
tab_model(mod1.3)
emmeans(mod1.3, pairwise~microsite|site_code)


###winter has one year only so no need to add to code. 
mod1.4<-glm(abundance~microsite%in%site_code, data = microclimate_animals_compiled_winter)
anova(mod1.4, test = "Chisq")
tab_model(mod1.4)
emmeans(mod1.4, pairwise~microsite|site_code)
          
mod1.5<-glm(richness~microsite %in% site_code, data = microclimate_animals_compiled_winter)
anova(mod1.5, test = "Chisq")
tab_model(mod1.5)
emmeans(mod1.5, pairwise~microsite|site_code)
          
mod1.6<-glm(evenness~microsite %in% site_code, data = microclimate_animals_compiled_winter)
anova(mod1.6, test = "Chisq")
tab_model(mod1.6)
emmeans(mod1.3, pairwise~microsite|site_code)
```

```{r}
###GLMs
###Animals associate with shrubs and shelters more than the open because they are cooler, more humid, and experience less direct solar radiation.
library(performance)
library(emmeans)


mod2.1<-glm(abundance~mean_humidity+mean_intensity+microsite+ (1 | year) , data = microclimate_animals_compiled)
summary(mod2.1)
anova(mod2.1, test = "Chisq")
tab_model(mod2.1)
check_collinearity(mod2.1)###low collinearity and humidity has a lower AIC score
###not siginficant for abundance
###when you include site_code in microite the model results in NA


mod2.2<-glm(richness~mean_humidity+mean_intensity+microsite+ (1 | year) , data = microclimate_animals_compiled)
summary(mod2.2)
anova(mod2.2, test = "Chisq")
tab_model(mod2.2)
check_collinearity(mod2.2)###low collinearity
###intensity signiicant for abundance


mod2.3<-glm(evenness~mean_humidity+mean_intensity+microsite+ (1 | year) , data = microclimate_animals_compiled)
summary(mod2.3)
anova(mod2.3, test = "Chisq")
tab_model(mod2.3)
check_collinearity(mod2.3)###low collinearity
###intensity and humidity both significant

###AIC was lower when humidity was used as predictor not temperature.



###winter does not have humidity so we use temp.
mod2.4<-glm(abundance~mean_temp+mean_intensity+ microsite, data = microclimate_animals_compiled_winter)
anova(mod2.4, test = "Chisq")
tab_model(mod2.4)
emmeans(mod2.4, pairwise~microsite)
          
mod2.5<-glm(richness~mean_temp+mean_intensity+ microsite, data = microclimate_animals_compiled_winter)
anova(mod2.5, test = "Chisq")
tab_model(mod2.5)
emmeans(mod2.5, pairwise~microsite)
          
mod2.6<-glm(evenness~mean_temp+mean_intensity+ microsite, data = microclimate_animals_compiled_winter)
anova(mod2.6, test = "Chisq")
tab_model(mod2.6)
emmeans(mod2.6, pairwise~microsite)

```

```{r}
###Run a PCA for summarized climate data.
library(corrr)
library("FactoMineR")
library(devtools)
library(factoextra)

###create a table with only the microclimatic variables from the summarized data.

microclimate_summarized_pca <- microclimate_animals_compiled[,6:8]
microclimate_summarized_pca<-microclimate_summarized_pca %>% drop_na(3)


data_normalized_summarized <- scale(microclimate_summarized_pca)
head(data_normalized_summarized)

corr_matrix_summarized <- cor(data_normalized_summarized)
data.pca.summarized <- princomp(corr_matrix_summarized)
summary(data.pca.summarized)

data.pca.summarized$loadings[, 1:2]


fviz_cos2(data.pca.summarized, choice = "var", axes = 1:2)

fviz_pca_var(data.pca.summarized, col.var = "cos2",
            gradient.cols = c("black", "orange", "green"),
            repel = TRUE) 
###mean temp and humidity are positively, correlated.
###mean temp and humidity are negatively correlated with intensity.
###mean temp and humidity contribute equally to PC1 and PC2, and both more than intensity.


fviz_eig(data.pca.summarized, addlabels = TRUE)
###PC1 contains 69% percent of the total information of the data.
###Eigenvalues of PC1 too small to just use in models.
```

```{r}
###SPRING
ggplot(microclimate_animals_compiled, aes(x = site_code, y = mean_temp, fill = microsite)) +
  geom_boxplot() + stat_summary(fun = mean, geom = "point", shape = 18, size = 2, position = position_dodge(width = 0.75 )) + labs(
       x = "Site",
       y = "Temperature (°C)", fill = "Microsite") + theme_classic() + theme_classic() + theme(text = element_text(size = 12), panel.border = element_rect(color = "black", fill = NA, size = 1.5), axis.text = element_text(size = 6)) + theme(aspect.ratio = 1) +ggtitle ('A') 

ggplot(microclimate_animals_compiled, aes(x = site_code, y = mean_humidity, fill = microsite)) +
  geom_boxplot() + stat_summary(fun = mean, geom = "point", shape = 18, size = 2, position = position_dodge(width = 0.75 )) + labs(
       x = "Site",
       y = "Humidity (%)", fill = "Microsite") + theme_classic() + theme_classic() + theme(text = element_text(size = 12), panel.border = element_rect(color = "black", fill = NA, size = 1.5), axis.text = element_text(size = 6)) + theme(aspect.ratio = 1)+ ggtitle('B') 

ggplot(microclimate_animals_compiled, aes(x = site_code, y = mean_intensity, fill = microsite)) +
  geom_boxplot() + stat_summary(fun = mean, geom = "point", shape = 18, size = 2, position = position_dodge(width = 0.75 )) + labs(
       x = "Site",
       y = "Radiation (lum/ft²)", fill = "Microsite") + theme_classic() + theme_classic() + theme(text = element_text(size = 12), panel.border = element_rect(color = "black", fill = NA, size = 1.5), axis.text = element_text(size = 6)) + theme(aspect.ratio = 1)+ ggtitle ('C')
```


```{r}
ggplot(microclimate_animals_compiled, aes(x=abundance, y=mean_temp, fill = microsite)) + 
  geom_boxplot()+ xlab("Abundance") +
  ylab("Temperature (°C)") +
  labs(fill = "Microsite") + theme_classic()+ theme(panel.border = element_rect(color = "black",
                                    fill = NA,
                                    size = 1)) + stat_summary(fun=mean, colour="black", geom="point", shape=18, size=3,show_guide = FALSE) + facet_wrap(~site_code)

ggplot(microclimate_animals_compiled, aes(x=abundance, y=mean_humidity, fill = microsite)) + 
  geom_boxplot()+ xlab("Abundance") +
  ylab("Humidity (%)") +
  labs(fill = "Microsite") + theme_classic()+ theme(panel.border = element_rect(color = "black",
                                    fill = NA,
                                    size = 1)) + stat_summary(fun=mean, colour="black", geom="point", shape=18, size=3,show_guide = FALSE) + facet_wrap(~site_code)

ggplot(microclimate_animals_compiled, aes(x=abundance, y=mean_intensity, fill = microsite)) + 
  geom_boxplot()+ xlab("Abundance") +
  ylab("Radiation (lum/ft²)") +
  labs(fill = "Microsite") + theme_classic()+ theme(panel.border = element_rect(color = "black",
                                    fill = NA,
                                    size = 1)) + stat_summary(fun=mean, colour="black", geom="point", shape=18, size=3,show_guide = FALSE) + facet_wrap(~site_code)




ggplot(microclimate_animals_compiled, aes(x=richness, y=mean_temp, fill = microsite)) + 
  geom_boxplot()+ xlab("Richness") +
  ylab("Temperature (°C)") +
  labs(fill = "Microsite") + theme_classic()+ theme(panel.border = element_rect(color = "black",
                                    fill = NA,
                                    size = 1)) + stat_summary(fun=mean, colour="black", geom="point", shape=18, size=3,show_guide = FALSE) + facet_wrap(~site_code)

ggplot(microclimate_animals_compiled, aes(x=richness, y=mean_humidity, fill = microsite)) + 
  geom_boxplot()+ xlab("Richness") +
  ylab("Humidity (%)") +
  labs(fill = "Microsite") + theme_classic()+ theme(panel.border = element_rect(color = "black",
                                    fill = NA,
                                    size = 1)) + stat_summary(fun=mean, colour="black", geom="point", shape=18, size=3,show_guide = FALSE) + facet_wrap(~site_code)

ggplot(microclimate_animals_compiled, aes(x=richness, y=mean_intensity, fill = microsite)) + 
  geom_boxplot()+ xlab("Richness") +
  ylab("Radiation (lum/ft²)") +
  labs(fill = "Microsite") + theme_classic()+ theme(panel.border = element_rect(color = "black",
                                    fill = NA,
                                    size = 1)) + stat_summary(fun=mean, colour="black", geom="point", shape=18, size=3,show_guide = FALSE) + facet_wrap(~site_code)



ggplot(microclimate_animals_compiled, aes(x=evenness, y=mean_humidity, fill = microsite)) + 
  geom_boxplot()+ xlab("Evenness") +
  ylab("Humidity (%)") +
  labs(fill = "Microsite") + theme_classic()+ theme(panel.border = element_rect(color = "black",
                                    fill = NA,
                                    size = 1)) + stat_summary(fun=mean, colour="black", geom="point", shape=18, size=3,show_guide = FALSE) + facet_wrap(~site_code)

```

```{r}
ggplot(microclimate_animals_compiled, aes(x=microsite, y=abundance, fill = microsite)) + 
  geom_boxplot()+ xlab("Microsite") +
  ylab("Abundance") +
  labs(fill = "Microsite") + theme_classic()+ theme(panel.border = element_rect(color = "black",
                                    fill = NA,
                                    size = 1)) + stat_summary(fun=mean, colour="black", geom="point", shape=18, size=3,show_guide = FALSE) + ggtitle('A') + theme(legend.position = "none")


ggplot(microclimate_animals_compiled, aes(x=microsite, y=richness, fill = microsite)) + 
  geom_boxplot()+ xlab("Microsite") +
  ylab("Richness") +
  labs(fill = "Microsite") + theme_classic()+ theme(panel.border = element_rect(color = "black",
                                    fill = NA,
                                    size = 1)) + stat_summary(fun=mean, colour="black", geom="point", shape=18, size=3,show_guide = FALSE) + ggtitle('B') + theme(legend.position = "none")


ggplot(microclimate_animals_compiled, aes(x=microsite, y=evenness, fill = microsite)) + 
  geom_boxplot()+ xlab("Microsite") +
  ylab("Evenness") +
  labs(fill = "Microsite") + theme_classic()+ theme(panel.border = element_rect(color = "black",
                                    fill = NA,
                                    size = 1)) + stat_summary(fun=mean, colour="black", geom="point", shape=18, size=3,show_guide = FALSE) + ggtitle('C') + theme(legend.position = "none")
library(patchwork)





ggplot(microclimate_animals_compiled, aes(x=abundance, y=mean_humidity, fill = microsite)) + 
  geom_boxplot()+ xlab("Abundance") +
  ylab("Humidity (%)") +
  labs(fill = "Microsite") + theme_classic()+ theme(panel.border = element_rect(color = "black",
                                    fill = NA,
                                
                                    size = 1)) + stat_summary(fun=mean, colour="black", geom="point", shape=18, size=3,show_guide = FALSE) + ggtitle ('A')

ggplot(microclimate_animals_compiled, aes(x=richness, y=mean_humidity, fill = microsite)) + 
  geom_boxplot()+ xlab("Richness") +
  ylab("Humidity (%)") +
  labs(fill = "Microsite") + theme_classic()+ theme(panel.border = element_rect(color = "black",
                                    fill = NA,
                                    size = 1)) + stat_summary(fun=mean, colour="black", geom="point", shape=18, size=3,show_guide = FALSE) + ggtitle ('B') +theme(legend.position = "none")

ggplot(microclimate_animals_compiled, aes(x=evenness, y=mean_humidity, fill = microsite)) + 
  geom_boxplot()+ xlab("Evenness") +
  ylab("Humidity (%)") +
  labs(fill = "Microsite") + theme_classic()+ theme(panel.border = element_rect(color = "black",
                                    fill = NA,
                                    size = 1)) + stat_summary(fun=mean, colour="black", geom="point", shape=18, size=3,show_guide = FALSE) + ggtitle ('C') +  theme(legend.position = "none")


ggplot(microclimate_animals_compiled, aes((abundance), mean_humidity, color=microsite)) + xlab("Abundance") + ylab ("Humidity (%) ")+ theme_classic()+ theme(axis.text=element_text(size=12))+  stat_smooth(method = "lm", formula = y ~ x)+ stat_summary(fun=mean, geom="point", size=2)+ labs(color="Microsite")+ theme(panel.border = element_rect(color = "black",
                                    fill = NA,
                                    size = 1)) +ggtitle ('A')

ggplot(microclimate_animals_compiled, aes((richness), mean_humidity, color=microsite)) + xlab("Richness") + ylab ("Humidity (%)")+ theme_classic()+ theme(axis.text=element_text(size=12))+  stat_smooth(method = "lm", formula = y ~ x)+ stat_summary(fun=mean, geom="point", size=2)+ labs(color="Microsite")+ theme(panel.border = element_rect(color = "black",
                                    fill = NA,
                                    size = 1)) + ggtitle ('B') +theme(legend.position = "none")


ggplot(microclimate_animals_compiled, aes((evenness), mean_humidity, color=microsite)) + xlab("Evenness") + ylab ("Humidity (%)")+ theme_classic()+ theme(axis.text=element_text(size=12))+  stat_smooth(method = "lm", formula = y ~ x)+ stat_summary(fun=mean, geom="point", size=2)+ labs(color="Microsite")+ theme(panel.border = element_rect(color = "black",
                                    fill = NA,
                                    size = 1)) + ggtitle('C')+ theme(legend.position = "none")


ggplot(microclimate_animals_compiled, aes((abundance), mean_temp, color=microsite)) + xlab("Abundance") + ylab ("Temperature (°C)")+ theme_classic()+ theme(axis.text=element_text(size=12))+  stat_smooth(method = "lm", formula = y ~ x)+ stat_summary(fun=mean, geom="point", size=2)+ labs(color="Microsite")+ theme(panel.border = element_rect(color = "black",
                                    fill = NA,
                                    size = 1)) +ggtitle ('A')

ggplot(microclimate_animals_compiled, aes((richness), mean_temp, color=microsite)) + xlab("Richness") + ylab ("Temperature (°C)")+ theme_classic()+ theme(axis.text=element_text(size=12))+  stat_smooth(method = "lm", formula = y ~ x)+ stat_summary(fun=mean, geom="point", size=2)+ labs(color="Microsite")+ theme(panel.border = element_rect(color = "black",
                                    fill = NA,
                                    size = 1)) + ggtitle ('B') +theme(legend.position = "none")


ggplot(microclimate_animals_compiled, aes((evenness), mean_temp, color=microsite)) + xlab("Evenness") + ylab ("Temperature (°C)")+ theme_classic()+ theme(axis.text=element_text(size=12))+  stat_smooth(method = "lm", formula = y ~ x)+ stat_summary(fun=mean, geom="point", size=2)+ labs(color="Microsite")+ theme(panel.border = element_rect(color = "black",
                                    fill = NA,
                                    size = 1)) + ggtitle('C')+ theme(legend.position = "none")



ggplot(microclimate_animals_compiled, aes((abundance), mean_intensity, color=microsite)) + xlab("Abundance") + ylab ("Radiation (lum/ft²)")+ theme_classic()+ theme(axis.text=element_text(size=12))+  stat_smooth(method = "lm", formula = y ~ x)+ stat_summary(fun=mean, geom="point", size=2)+ labs(color="Microsite")+ theme(panel.border = element_rect(color = "black",
                                    fill = NA,
                                    size = 1)) +ggtitle ('A')

ggplot(microclimate_animals_compiled, aes((richness), mean_intensity, color=microsite)) + xlab("Richness") + ylab ("Radiation (lum/ft²)")+ theme_classic()+ theme(axis.text=element_text(size=12))+  stat_smooth(method = "lm", formula = y ~ x)+ stat_summary(fun=mean, geom="point", size=2)+ labs(color="Microsite")+ theme(panel.border = element_rect(color = "black",
                                    fill = NA,
                                    size = 1)) + ggtitle ('B') +theme(legend.position = "none")


ggplot(microclimate_animals_compiled, aes((evenness), mean_intensity, color=microsite)) + xlab("Evenness") + ylab ("Radiation (lum/ft²)")+ theme_classic()+ theme(axis.text=element_text(size=12))+  stat_smooth(method = "lm", formula = y ~ x)+ stat_summary(fun
                                                                                                                                                                                                                                                               =mean, geom="point", size=2)+ labs(color="Microsite")+ theme(panel.border = element_rect(color = "black",
                                    fill = NA,
                                    size = 1)) + ggtitle('C')+ theme(legend.position = "none")




```

\`\`\`
